spring.application.name=ecom
# spring.h2.console.enabled=true
# Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/ecom?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA (The Tool that creates tables for you)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8088
